### ISSUE TITLE
Support for updating live machines using the talos provider

### ISSUE THREAD

**Issue by Drakonis** [hcloud-talos/terraform-hcloud-talos#60]
Right now, all provisioned machines use only the configurations assigned to user_data at creation time, any further changes have to be applied through `talosctl`.

The talos provider appears to provide the ability to apply any modifications to machine configurations in the form of [talos_machine_configuration_apply](https://registry.terraform.io/providers/siderolabs/talos/latest/docs/resources/machine_configuration_apply).

**Comment by mrclrchtr** [comment]
I've been thinking about this for a while, whether it's somehow possible. Unfortunately, we already need the config when creating the server. As far as I know, we can't start it first and then deploy the config. 

Maybe we can deploy the same config again after the start. Then we could customize it later.

**Comment by micheljung** [comment]
> Unfortunately, we already need the config when creating the server.

Why?

**Comment by mrclrchtr** [comment]
As far as I know because of:

```  
user_data          = data.talos_machine_configuration.control_plane[each.value.name].machine_configuration
```
https://github.com/hcloud-talos/terraform-hcloud-talos/blob/8f33e41afa67e779790e87414c7dd645b650089a/server.tf#L56

But I'm not 100% sure. 

Perhaps what Roxedus says [here](https://github.com/hcloud-talos/terraform-hcloud-talos/discussions/68) also offers a new possibility for this problem.

I would love to try it out, but at the moment I don't have the time because of other projects.

**Comment by mrclrchtr** [comment]
## Follow-up from the upgrades after v3.4.15

Talos provider 0.12.0 adds `talos_machine`, which can apply configuration, detect drift, and upgrade Talos in place. This issue already covers live machine updates, so it should track the new option instead of creating a duplicate.

### Tasks
- [ ] Evaluate an opt-in `talos_machine` mode while preserving current behavior by default.
- [ ] Test adoption of existing nodes configured through Hetzner `user_data`; check that the first apply does not cause an unexpected configuration change or reboot.
- [ ] Separate the configuration-generation Talos version from the desired OS installer image.
- [ ] Sequence control-plane OS upgrades to preserve etcd quorum. A simple `for_each` does not provide this sequence.
- [ ] Supply kubeconfig access for drain operations and test worker upgrades.
- [ ] Define behavior for manual configuration changes, manual upgrades, timeouts, and failed upgrades.
- [ ] Keep destructive reset behavior disabled unless explicitly requested.
- [ ] Test fresh clusters, existing clusters, HA, scale-up, and recovery in a disposable environment.
- [ ] Document migration and Terraform/OpenTofu support. Write-only arguments require separate compatibility checks.

Coordinate with the new Kubernetes upgrade issue: use `ignore_kubernetes_upgrade_drift` when both new resources manage the cluster, and document that upstream marks it experimental.

Sources:
- https://github.com/siderolabs/terraform-provider-talos/releases/tag/v0.12.0
- https://github.com/siderolabs/terraform-provider-talos/blob/v0.12.0/docs/resources/machine.md

Related Kubernetes upgrade task: https://github.com/hcloud-talos/terraform-hcloud-talos/issues/585
